name       : darkradiant
version    : 2.6.0
release    : 3
source     :
    - https://github.com/codereader/DarkRadiant/archive/2.6.0.tar.gz : e46dc10a3a7521d64ba30a2eddfe2c8b75ef3ec12f155833e565ce04d21693ea
license    : GPL-2.0-or-later
component  : games.action
summary    : DarkRadiant is the map editor for The Dark Mod and other idTech4/Doom3-based games
description: |
    DarkRadiant is a level (map) editor for the The Dark Mod, an open-source Doom 3 modification
builddeps  :
    - pkgconfig(freealut)
    - pkgconfig(ftgl)
    - pkgconfig(glew)
    - pkgconfig(libturbojpeg)
    - pkgconfig(vorbis)
    - pkgconfig(libxml-2.0)
    - pkgconfig(sigc++-2.0)
    - wxwidgets-devel
setup      : |
    %autogen --enable-darkmod-plugins
build      : |
    %make
install    : |
    %make_install

